Default bucket salt
Kinto/kinto pull request #2647
Opened 2020-10-31 01:22 UTC by feiming

Fixes #

- [ ] Add documentation.
- [ ] Add tests.
- [ ] Add a changelog entry.
- [ ] Add your name in the contributors file.
- [ ] If you changed the HTTP API, update the [API_VERSION](https://github.com/Kinto/kinto/blob/master/kinto/__init__.py#L15) constant and add an API changelog entry [in the docs](https://github.com/Kinto/kinto/blob/master/docs/api/index.rst)
- [ ] If you added a new configuration setting, update the [`kinto.tpl`](https://github.com/Kinto/kinto/blob/master/kinto/config/kinto.tpl) file with it.

2020-10-31 02:11 UTC, feiming commented
please add `hacktoberfest-accepted` label to this PR

2020-10-31 08:54 UTC, Natim commented
Thank you for you work on this !

2020-10-31 08:58 UTC, Natim commented on tests/test_configuration/test.ini
> +kinto.default_bucket_ID_salt = bucket_id_salt
```suggestion
kinto.default_bucket_id_salt = bucket_id_salt
```

2020-10-31 09:02 UTC, Natim requested changes
Do you mind adding a line in the documentation next to `userid_hmac_secret` (see docs/configuration/settings.rst)
I wonder if to be consistent we should call the config `default_bucket_hmac_secret` rather than `default_bucket_id_salt`

2020-10-31 11:10 UTC, feiming commented
@Natim I've renamed all default_bucket_ID_salt to default_bucket_id_salt

2020-11-02 08:49 UTC, Natim commented on kinto/config/__init__.py
> +    values["bucket_id_salt"] = core_utils.random_urlsafe(32)
Let's use the same function.

```suggestion
    values["bucket_id_salt"] = core_utils.random_bytes_hex(32)
```

2020-11-02 08:50 UTC, Natim commented on kinto/core/utils.py
> +
If we use the existing method, we don't need this one.

```suggestion
```

2020-11-02 08:51 UTC, Natim commented
I would add a test to see that when the default_bucket_hmac secret is not defined it uses the user_hmac one and that when it is defined it doesn't.

2020-11-02 09:00 UTC, feiming commented
> I would add a test to see that when the default_bucket_hmac secret is not defined it uses the user_hmac one and that when it is defined it doesn't.

like this? https://github.com/Kinto/kinto/pull/2647/files#diff-79caf24359b02ce1c1bed59ce1514942e785f4498d3474758287796bb5dd5af7R38

2020-11-02 11:19 UTC, leplatrem approved these changes

2020-11-02 11:19 UTC, leplatrem commented on docs/configuration/settings.rst
> +Bucket IDs are generated using salt declared in `default_bucket_hmac_secret`.
nit: use double back ticks in RST

2020-11-02 16:27 UTC, feiming commented
> I would add a test to see that when the default_bucket_hmac secret is not defined it uses the user_hmac one and that when it is defined it doesn't.

I'm not too sure how to test it. Does something like this work?

```
    def test_default_bucket_hmac_secret_define(self):
        settings = {"default_bucket_hmac_secret":"bucket_id_salt","userid_hmac_secret":"secret"}
        secret = settings.get("default_bucket_hmac_secret", settings["userid_hmac_secret"])

        self.assertEqual(secret,"bucket_id_salt")

    def test_default_bucket_hmac_secret_not_define_fallback_to_userid_hmac_secret(self):
        settings = {"userid_hmac_secret":"super_secret"}
        secret = settings.get("default_bucket_hmac_secret", settings["userid_hmac_secret"])

        self.assertEqual(secret,"super_secret")
```

2020-11-03 14:37 UTC, leplatrem commented
Maybe you could test that `hmac_digest()` is called with a value or another?

2020-11-04 06:19 UTC, feiming commented
I had to mock `hmac_secret` because the default `hmac_secret` is an empty string. I also had to delete `default_bucket_hmac_secret` to test if it's not defined.

I hope this satisfied the test case.

2020-11-13 07:16 UTC, feiming commented
@Natim I've added the test 

> I would add a test to see that when the default_bucket_hmac secret is not defined it uses the user_hmac one and that when it is defined it doesn't.

@Natim I've added the test

2020-12-21 14:35 UTC, merged